import { writable } from "svelte/store";

export type LanguageKey = "es" | "en" | "de" | "fr" | "it" | "zh" | "ja" | "ru";

export const sidebarOpen = writable(false);
export const selectedFilter = writable("all");
export const selectedLanguage = writable<LanguageKey>("es");

export const translations = {
  es: {
    all: "Todos",
    offerings: "Ofrendas",
    routes: "Rutas",
    information: "Información",
    parking: "Estacionamiento",
    hotel: "Hotel",
    language: "Idioma",
    spanish: "Español",
    english: "Inglés",
    german: "Alemán",
    french: "Francés",
    italian: "Italiano",
    chinese: "Chino",
    japanese: "Japonés",
    russian: "Ruso",
  },
  en: {
    all: "All",
    offerings: "Offerings",
    routes: "Routes",
    information: "Information",
    parking: "Parking",
    hotel: "Hotel",
    language: "Language",
    spanish: "Spanish",
    english: "English",
    german: "German",
    french: "French",
    italian: "Italian",
    chinese: "Chinese",
    japanese: "Japanese",
    russian: "Russian",
  },
  de: {
    all: "Alle",
    offerings: "Opfergaben",
    routes: "Routen",
    information: "Information",
    parking: "Parkplatz",
    hotel: "Hotel",
    language: "Sprache",
    spanish: "Spanisch",
    english: "Englisch",
    german: "Deutsch",
    french: "Französisch",
    italian: "Italienisch",
    chinese: "Chinesisch",
    japanese: "Japanisch",
    russian: "Russisch",
  },
  fr: {
    all: "Tous",
    offerings: "Offrandes",
    routes: "Itinéraires",
    information: "Information",
    parking: "Parking",
    hotel: "Hôtel",
    language: "Langue",
    spanish: "Espagnol",
    english: "Anglais",
    german: "Allemand",
    french: "Français",
    italian: "Italien",
    chinese: "Chinois",
    japanese: "Japonais",
    russian: "Russe",
  },
  it: {
    all: "Tutti",
    offerings: "Offerte",
    routes: "Percorsi",
    information: "Informazione",
    parking: "Parcheggio",
    hotel: "Hotel",
    language: "Lingua",
    spanish: "Spagnolo",
    english: "Inglese",
    german: "Tedesco",
    french: "Francese",
    italian: "Italiano",
    chinese: "Cinese",
    japanese: "Giapponese",
    russian: "Russo",
  },
  zh: {
    all: "全部",
    offerings: "祭品",
    routes: "路线",
    information: "信息",
    parking: "停车场",
    hotel: "酒店",
    language: "语言",
    spanish: "西班牙语",
    english: "英语",
    german: "德语",
    french: "法语",
    italian: "意大利语",
    chinese: "中文",
    japanese: "日语",
    russian: "俄语",
  },
  ja: {
    all: "すべて",
    offerings: "供物",
    routes: "ルート",
    information: "情報",
    parking: "駐車場",
    hotel: "ホテル",
    language: "言語",
    spanish: "スペイン語",
    english: "英語",
    german: "ドイツ語",
    french: "フランス語",
    italian: "イタリア語",
    chinese: "中国語",
    japanese: "日本語",
    russian: "ロシア語",
  },
  ru: {
    all: "Все",
    offerings: "Подношения",
    routes: "Маршруты",
    information: "Информация",
    parking: "Парковка",
    hotel: "Отель",
    language: "Язык",
    spanish: "Испанский",
    english: "Английский",
    german: "Немецкий",
    french: "Французский",
    italian: "Итальянский",
    chinese: "Китайский",
    japanese: "Японский",
    russian: "Русский",
  },
};
