import { writable } from "svelte/store";
import type { LanguageKey } from "./generals";

export interface Location {
  id: number | string;
  name: {
    es: string;
    en: string;
    de: string;
    fr: string;
    it: string;
    zh: string;
    ja: string;
    ru: string;
  };
  type: "ofrenda" | "information" | "parking" | "hotel" | "route";
  lat: number;
  lng: number;
  description?: {
    es: string;
    en: string;
    de: string;
    fr: string;
    it: string;
    zh: string;
    ja: string;
    ru: string;
  };
  // Para rutas
  routePoints?: [number, number][];
  routeColor?: string;
  // Para puntos de interés en la ruta
  points?: {
    name: {
      es: string;
      en: string;
      de: string;
      fr: string;
      it: string;
      zh: string;
      ja: string;
      ru: string;
    };
    description: {
      es: string;
      en: string;
      de: string;
      fr: string;
      it: string;
      zh: string;
      ja: string;
      ru: string;
    };
    lat: number;
    lng: number;
    image?: string;
  }[];
  image?: string;
}

export const locations = writable<Location[]>([
  {
    id: 1,
    name: {
      es: "Juan Rosas Flores",
      en: "Juan Rosas Flores",
      de: "Juan Rosas Flores",
      fr: "Juan Rosas Flores",
      it: "Juan Rosas Flores",
      zh: "Juan Rosas Flores",
      ja: "Juan Rosas Flores",
      ru: "Juan Rosas Flores",
    },
    lat: 18.770334898464128,
    lng: -98.54427927201222,
    type: "ofrenda",
  },
  {
    id: 2,
    name: {
      es: "Ariel García Toribio",
      en: "Ariel García Toribio",
      de: "Ariel García Toribio",
      fr: "Ariel García Toribio",
      it: "Ariel García Toribio",
      zh: "Ariel García Toribio",
      ja: "Ariel García Toribio",
      ru: "Ariel García Toribio",
    },
    lat: 18.777475891161036,
    lng: -98.54691648975597,
    type: "ofrenda",
  },
  {
    id: 3,
    name: {
      es: "Francisco Jimenez Castillo",
      en: "Francisco Jimenez Castillo",
      de: "Francisco Jimenez Castillo",
      fr: "Francisco Jimenez Castillo",
      it: "Francisco Jimenez Castillo",
      zh: "Francisco Jimenez Castillo",
      ja: "Francisco Jimenez Castillo",
      ru: "Francisco Jimenez Castillo",
    },
    lat: 18.768131362326173,
    lng: -98.53662781469096,
    type: "ofrenda",
  },
  {
    id: 4,
    name: {
      es: "Petra Molina Dominguez",
      en: "Petra Molina Dominguez",
      de: "Petra Molina Dominguez",
      fr: "Petra Molina Dominguez",
      it: "Petra Molina Dominguez",
      zh: "Petra Molina Dominguez",
      ja: "Petra Molina Dominguez",
      ru: "Petra Molina Dominguez",
    },
    lat: 18.769324293748806,
    lng: -98.53797367053448,
    type: "ofrenda",
  },
  {
    id: 5,
    name: {
      es: "Paula Chapero Vega",
      en: "Paula Chapero Vega",
      de: "Paula Chapero Vega",
      fr: "Paula Chapero Vega",
      it: "Paula Chapero Vega",
      zh: "Paula Chapero Vega",
      ja: "Paula Chapero Vega",
      ru: "Paula Chapero Vega",
    },
    lat: 18.76848623239249,
    lng: -98.53914847808667,
    type: "ofrenda",
  },
  {
    id: 6,
    name: {
      es: "M. Patricia Rivera Cruz",
      en: "M. Patricia Rivera Cruz",
      de: "M. Patricia Rivera Cruz",
      fr: "M. Patricia Rivera Cruz",
      it: "M. Patricia Rivera Cruz",
      zh: "M. Patricia Rivera Cruz",
      ja: "M. Patricia Rivera Cruz",
      ru: "M. Patricia Rivera Cruz",
    },
    lat: 18.769568092646224,
    lng: -98.53968223765531,
    type: "ofrenda",
  },
  {
    id: 7,
    name: {
      es: "Luis Molina Bautista",
      en: "Luis Molina Bautista",
      de: "Luis Molina Bautista",
      fr: "Luis Molina Bautista",
      it: "Luis Molina Bautista",
      zh: "Luis Molina Bautista",
      ja: "Luis Molina Bautista",
      ru: "Luis Molina Bautista",
    },
    lat: 18.768765444122035,
    lng: -98.53974633903022,
    type: "ofrenda",
  },
  {
    id: 8,
    name: {
      es: "Rufina Flores Vivaldo",
      en: "Rufina Flores Vivaldo",
      de: "Rufina Flores Vivaldo",
      fr: "Rufina Flores Vivaldo",
      it: "Rufina Flores Vivaldo",
      zh: "Rufina Flores Vivaldo",
      ja: "Rufina Flores Vivaldo",
      ru: "Rufina Flores Vivaldo",
    },
    lat: 18.768501327379486,
    lng: -98.54013257703313,
    type: "ofrenda",
  },
  {
    id: 9,
    name: {
      es: "Guadalupe Sosa Rodríguez",
      en: "Guadalupe Sosa Rodríguez",
      de: "Guadalupe Sosa Rodríguez",
      fr: "Guadalupe Sosa Rodríguez",
      it: "Guadalupe Sosa Rodríguez",
      zh: "Guadalupe Sosa Rodríguez",
      ja: "Guadalupe Sosa Rodríguez",
      ru: "Guadalupe Sosa Rodríguez",
    },
    lat: 18.767503409653678,
    lng: -98.54008456893058,
    type: "ofrenda",
  },
  {
    id: 10,
    name: {
      es: "Enedina Dolores Sánchez",
      en: "Enedina Dolores Sánchez",
      de: "Enedina Dolores Sánchez",
      fr: "Enedina Dolores Sánchez",
      it: "Enedina Dolores Sánchez",
      zh: "Enedina Dolores Sánchez",
      ja: "Enedina Dolores Sánchez",
      ru: "Enedina Dolores Sánchez",
    },
    lat: 18.76602789500967,
    lng: -98.54035010761496,
    type: "ofrenda",
  },
  {
    id: 11,
    name: {
      es: "Francisco Ramírez Yáñez",
      en: "Francisco Ramírez Yáñez",
      de: "Francisco Ramírez Yáñez",
      fr: "Francisco Ramírez Yáñez",
      it: "Francisco Ramírez Yáñez",
      zh: "Francisco Ramírez Yáñez",
      ja: "Francisco Ramírez Yáñez",
      ru: "Francisco Ramírez Yáñez",
    },
    lat: 18.765931389300512,
    lng: -98.54045739596901,
    type: "ofrenda",
  },
  {
    id: 12,
    name: {
      es: "Marina Pérez Avelino",
      en: "Marina Pérez Avelino",
      de: "Marina Pérez Avelino",
      fr: "Marina Pérez Avelino",
      it: "Marina Pérez Avelino",
      zh: "Marina Pérez Avelino",
      ja: "Marina Pérez Avelino",
      ru: "Marina Pérez Avelino",
    },
    lat: 18.76381494917972,
    lng: -98.54076850887289,
    type: "ofrenda",
  },
  {
    id: 13,
    name: {
      es: "Ana Maria Vargas Dolores",
      en: "Ana Maria Vargas Dolores",
      de: "Ana Maria Vargas Dolores",
      fr: "Ana Maria Vargas Dolores",
      it: "Ana Maria Vargas Dolores",
      zh: "Ana Maria Vargas Dolores",
      ja: "Ana Maria Vargas Dolores",
      ru: "Ana Maria Vargas Dolores",
    },
    lat: 18.76654583481714,
    lng: -98.54206913176763,
    type: "ofrenda",
  },
  {
    id: 14,
    name: {
      es: "Bulfrano Sedeño",
      en: "Bulfrano Sedeño",
      de: "Bulfrano Sedeño",
      fr: "Bulfrano Sedeño",
      it: "Bulfrano Sedeño",
      zh: "Bulfrano Sedeño",
      ja: "Bulfrano Sedeño",
      ru: "Bulfrano Sedeño",
    },
    lat: 18.768216893473824,
    lng: -98.54308300679253,
    type: "ofrenda",
  },
  {
    id: 15,
    name: {
      es: "Herminia Mejía Avelar",
      en: "Herminia Mejía Avelar",
      de: "Herminia Mejía Avelar",
      fr: "Herminia Mejía Avelar",
      it: "Herminia Mejía Avelar",
      zh: "Herminia Mejía Avelar",
      ja: "Herminia Mejía Avelar",
      ru: "Herminia Mejía Avelar",
    },
    lat: 18.76900416461982,
    lng: -98.54331904117346,
    type: "ofrenda",
  },
  {
    id: 16,
    name: {
      es: "Francisca Baltazar Santos",
      en: "Francisca Baltazar Santos",
      de: "Francisca Baltazar Santos",
      fr: "Francisca Baltazar Santos",
      it: "Francisca Baltazar Santos",
      zh: "Francisca Baltazar Santos",
      ja: "Francisca Baltazar Santos",
      ru: "Francisca Baltazar Santos",
    },
    lat: 18.769151460110763,
    lng: -98.54343169395962,
    type: "ofrenda",
  },
  {
    id: 17,
    name: {
      es: "Julia Morales Confesor",
      en: "Julia Morales Confesor",
      de: "Julia Morales Confesor",
      fr: "Julia Morales Confesor",
      it: "Julia Morales Confesor",
      zh: "Julia Morales Confesor",
      ja: "Julia Morales Confesor",
      ru: "Julia Morales Confesor",
    },
    lat: 18.769217489077825,
    lng: -98.54407542408406,
    type: "ofrenda",
  },
  {
    id: 18,
    name: {
      es: "Rogelio Aguilar Mejía",
      en: "Rogelio Aguilar Mejía",
      de: "Rogelio Aguilar Mejía",
      fr: "Rogelio Aguilar Mejía",
      it: "Rogelio Aguilar Mejía",
      zh: "Rogelio Aguilar Mejía",
      ja: "Rogelio Aguilar Mejía",
      ru: "Rogelio Aguilar Mejía",
    },
    lat: 18.768607989937966,
    lng: -98.54461723027211,
    type: "ofrenda",
  },
  {
    id: 19,
    name: {
      es: "Angela Rosales Viyaldo",
      en: "Angela Rosales Viyaldo",
      de: "Angela Rosales Viyaldo",
      fr: "Angela Rosales Viyaldo",
      it: "Angela Rosales Viyaldo",
      zh: "Angela Rosales Viyaldo",
      ja: "Angela Rosales Viyaldo",
      ru: "Angela Rosales Viyaldo",
    },
    lat: 18.76731787615786,
    lng: -98.54458504376589,
    type: "ofrenda",
  },
  {
    id: 20,
    name: {
      es: "Reyes Morales Castillo",
      en: "Reyes Morales Castillo",
      de: "Reyes Morales Castillo",
      fr: "Reyes Morales Castillo",
      it: "Reyes Morales Castillo",
      zh: "Reyes Morales Castillo",
      ja: "Reyes Morales Castillo",
      ru: "Reyes Morales Castillo",
    },
    lat: 18.77004030944074,
    lng: -98.54448311988497,
    type: "ofrenda",
  },
  {
    id: 21,
    name: {
      es: "Felipe Mendoza Arizpe",
      en: "Felipe Mendoza Arizpe",
      de: "Felipe Mendoza Arizpe",
      fr: "Felipe Mendoza Arizpe",
      it: "Felipe Mendoza Arizpe",
      zh: "Felipe Mendoza Arizpe",
      ja: "Felipe Mendoza Arizpe",
      ru: "Felipe Mendoza Arizpe",
    },
    lat: 18.77167338297446,
    lng: -98.54107430412724,
    type: "ofrenda",
  },
  {
    id: 22,
    name: {
      es: "Pedro Poblano Paredes",
      en: "Pedro Poblano Paredes",
      de: "Pedro Poblano Paredes",
      fr: "Pedro Poblano Paredes",
      it: "Pedro Poblano Paredes",
      zh: "Pedro Poblano Paredes",
      ja: "Pedro Poblano Paredes",
      ru: "Pedro Poblano Paredes",
    },
    lat: 18.774113861538353,
    lng: -98.54265412527589,
    type: "ofrenda",
  },
  {
    id: 23,
    name: {
      es: "Amelia Eustaquio Adalla",
      en: "Amelia Eustaquio Adalla",
      de: "Amelia Eustaquio Adalla",
      fr: "Amelia Eustaquio Adalla",
      it: "Amelia Eustaquio Adalla",
      zh: "Amelia Eustaquio Adalla",
      ja: "Amelia Eustaquio Adalla",
      ru: "Amelia Eustaquio Adalla",
    },
    lat: 18.77552327892154,
    lng: -98.54319324925508,
    type: "ofrenda",
  },
  {
    id: 24,
    name: {
      es: "Ignacio Peralta Soledad",
      en: "Ignacio Peralta Soledad",
      de: "Ignacio Peralta Soledad",
      fr: "Ignacio Peralta Soledad",
      it: "Ignacio Peralta Soledad",
      zh: "Ignacio Peralta Soledad",
      ja: "Ignacio Peralta Soledad",
      ru: "Ignacio Peralta Soledad",
    },
    lat: 18.774383048472053,
    lng: -98.54488304090842,
    type: "ofrenda",
  },
  {
    id: 25,
    name: {
      es: "Manuel Rojas Alonso",
      en: "Manuel Rojas Alonso",
      de: "Manuel Rojas Alonso",
      fr: "Manuel Rojas Alonso",
      it: "Manuel Rojas Alonso",
      zh: "Manuel Rojas Alonso",
      ja: "Manuel Rojas Alonso",
      ru: "Manuel Rojas Alonso",
    },
    lat: 18.775495344637882,
    lng: -98.54515930842015,
    type: "ofrenda",
  },
  {
    id: 26,
    name: {
      es: "Wilfrido Molina Dominguez",
      en: "Wilfrido Molina Dominguez",
      de: "Wilfrido Molina Dominguez",
      fr: "Wilfrido Molina Dominguez",
      it: "Wilfrido Molina Dominguez",
      zh: "Wilfrido Molina Dominguez",
      ja: "Wilfrido Molina Dominguez",
      ru: "Wilfrido Molina Dominguez",
    },
    lat: 18.77393609632654,
    lng: -98.5454784913471,
    type: "ofrenda",
  },
  {
    id: 27,
    name: {
      es: "Hugo Gracia Caballero",
      en: "Hugo Gracia Caballero",
      de: "Hugo Gracia Caballero",
      fr: "Hugo Gracia Caballero",
      it: "Hugo Gracia Caballero",
      zh: "Hugo Gracia Caballero",
      ja: "Hugo Gracia Caballero",
      ru: "Hugo Gracia Caballero",
    },
    lat: 18.774642076981305,
    lng: -98.5462187809902,
    type: "ofrenda",
  },
  {
    id: 28,
    name: {
      es: "J. Manuel Juárez Castillo",
      en: "J. Manuel Juárez Castillo",
      de: "J. Manuel Juárez Castillo",
      fr: "J. Manuel Juárez Castillo",
      it: "J. Manuel Juárez Castillo",
      zh: "J. Manuel Juárez Castillo",
      ja: "J. Manuel Juárez Castillo",
      ru: "J. Manuel Juárez Castillo",
    },
    lat: 18.77360895578451,
    lng: -98.54934319097077,
    type: "ofrenda",
  },
  {
    id: 29,
    name: {
      es: "Gregoria Camacho Romero",
      en: "Gregoria Camacho Romero",
      de: "Gregoria Camacho Romero",
      fr: "Gregoria Camacho Romero",
      it: "Gregoria Camacho Romero",
      zh: "Gregoria Camacho Romero",
      ja: "Gregoria Camacho Romero",
      ru: "Gregoria Camacho Romero",
    },
    lat: -18.7756789,
    lng: -98.5437901,
    type: "ofrenda",
  },
  {
    id: 30,
    name: {
      es: "M. Luisa Garcia Flores",
      en: "M. Luisa Garcia Flores",
      de: "M. Luisa Garcia Flores",
      fr: "M. Luisa Garcia Flores",
      it: "M. Luisa Garcia Flores",
      zh: "M. Luisa Garcia Flores",
      ja: "M. Luisa Garcia Flores",
      ru: "M. Luisa Garcia Flores",
    },
    lat: 18.76944097156124,
    lng: -98.53779369091438,
    type: "ofrenda",
  },
  {
    id: 31,
    name: {
      es: "Altar del Ex Convento",
      en: "Altar del Ex Convento",
      de: "Altar del Ex Convento",
      fr: "Altar del Ex Convento",
      it: "Altar del Ex Convento",
      zh: "Altar del Ex Convento",
      ja: "Altar del Ex Convento",
      ru: "Altar del Ex Convento",
    },
    lat: 18.770121717981272,
    lng: -98.54112258385567,
    type: "ofrenda",
  },
  {
    id: 32,
    name: {
      es: "Altar de Palacio Municipal",
      en: "Altar de Palacio Municipal",
      de: "Altar de Palacio Municipal",
      fr: "Altar de Palacio Municipal",
      it: "Altar de Palacio Municipal",
      zh: "Altar de Palacio Municipal",
      ja: "Altar de Palacio Municipal",
      ru: "Altar de Palacio Municipal",
    },
    lat: 18.770627089980806,
    lng: -98.54152491520921,
    type: "ofrenda",
  },
  {
    id: 33,
    name: {
      es: "Altar de Casa Palestina",
      en: "Altar de Casa Palestina",
      de: "Altar de Casa Palestina",
      fr: "Altar de Casa Palestina",
      it: "Altar de Casa Palestina",
      zh: "Altar de Casa Palestina",
      ja: "Altar de Casa Palestina",
      ru: "Altar de Casa Palestina",
    },
    lat: 18.770505191337527,
    lng: -98.54005774694149,
    type: "ofrenda",
  },
  {
    id: 34,
    name: {
      es: "Altar en Vida, Sra. Gudelina Vargas Luna",
      en: "Altar en Vida, Sra. Gudelina Vargas Luna",
      de: "Altar en Vida, Sra. Gudelina Vargas Luna",
      fr: "Altar en Vida, Sra. Gudelina Vargas Luna",
      it: "Altar en Vida, Sra. Gudelina Vargas Luna",
      zh: "Altar en Vida, Sra. Gudelina Vargas Luna",
      ja: "Altar en Vida, Sra. Gudelina Vargas Luna",
      ru: "Altar en Vida, Sra. Gudelina Vargas Luna",
    },
    lat: 18.767495648305854,
    lng: -98.54319565956432,
    type: "ofrenda",
  },
  {
    id: 35,
    name: {
      es: "Módulo información",
      en: "Information Module",
      de: "Informationsmodul",
      fr: "Module d'information",
      it: "Modulo informativo",
      zh: "信息模块",
      ja: "情報モジュール",
      ru: "Информационный модуль",
    },
    lat: 18.7704051,
    lng: -98.541396,
    type: "information",
  },
  {
    id: 36,
    name: {
      es: "Módulo información",
      en: "Information Module",
      de: "Informationsmodul",
      fr: "Module d'information",
      it: "Modulo informativo",
      zh: "信息模块",
      ja: "情報モジュール",
      ru: "Информационный модуль",
    },
    lat: 18.7698209,
    lng: -98.5415327,
    type: "information",
  },
  {
    id: 37,
    name: {
      es: "Estacionamiento",
      en: "Parking",
      de: "Parkplatz",
      fr: "Parking",
      it: "Parcheggio",
      zh: "停车场",
      ja: "駐車場",
      ru: "Парковка",
    },
    lat: 18.767523,
    lng: -98.5400888,
    type: "parking",
  },
  {
    id: 38,
    name: {
      es: "Hotel",
      en: "Hotel",
      de: "Hotel",
      fr: "Hôtel",
      it: "Hotel",
      zh: "酒店",
      ja: "ホテル",
      ru: "Отель",
    },
    lat: 18.7715102,
    lng: -98.5410685,
    type: "hotel",
  },
  {
    id: "route1",
    name: {
      es: "Camino de Flores",
      en: "Path of Flowers",
      de: "Blumenweg",
      fr: "Chemin des Fleurs",
      it: "Cammino dei Fiori",
      zh: "鲜花之路",
      ja: "花の道",
      ru: "Цветочная дорожка",
    },
    type: "route",
    lat: 18.768804,
    lng: -98.540597,
    description: {
      es: "Recorrido principal de entrada de flores, donde podrás ver hermosos arcos y decoraciones florales tradicionales. Un espectacular camino adornado con flores de cempasúchil y diferentes tipos de flores tradicionales.",
      en: "Main flower entrance route, where you can see beautiful arches and traditional floral decorations. A spectacular path adorned with marigold flowers and different types of traditional flowers.",
      de: "Haupteingang mit Blumen, wo Sie schöne Bögen und traditionelle Blumendekorationen sehen können. Ein spektakulärer Weg, geschmückt mit Ringelblumen und verschiedenen traditionellen Blumen.",
      fr: "Route principale d'entrée de fleurs, où vous pouvez voir de beaux arcs et des décorations florales traditionnelles. Un chemin spectaculaire orné de fleurs de souci et différents types de fleurs traditionnelles.",
      it: "Percorso principale d'ingresso fiorito, dove potrai vedere bellissimi archi e decorazioni floreali tradizionali. Un sentiero spettacolare adornato con fiori di calendula e diversi tipi di fiori tradizionali.",
      zh: "主要花卉入口路线，在这里您可以看到美丽的拱门和传统的花卉装饰。一条壮观的小路，装饰着万寿菊和各种传统花卉。",
      ja: "美しいアーチと伝統的な花の装飾を見ることができる、メインフラワーエントランスルート。マリーゴールドの花とさまざまな伝統的な花で飾られた壮観な道。",
      ru: "Главный цветочный входной маршрут, где вы можете увидеть красивые арки и традиционные цветочные украшения. Впечатляющая дорожка, украшенная цветами календулы и различными традиционными цветами.",
    },
    routePoints: [
      [18.768565, -98.5398857],
      [18.768815, -98.541554],
      [18.769732, -98.541468],
    ],
    routeColor: "#FF4136",
    image: "/arcos.png",
  },
  {
    id: "route2",
    name: {
      es: "Calle de las Tumbas Artificiales",
      en: "Street of Artificial Tombs",
      de: "Straße der künstlichen Gräber",
      fr: "Rue des Tombes Artificielles",
      it: "Via delle Tombe Artificiali",
      zh: "人造墓穴街",
      ja: "人工墓の通り",
      ru: "Улица искусственных гробниц",
    },
    type: "route",
    lat: 18.7714078,
    lng: -98.5410944,
    description: {
      es: "Recorrido por la calle donde encontrarás impresionantes tumbas artificiales y decoraciones tradicionales del Día de Muertos.",
      en: "A route through the street where you'll find impressive artificial tombs and traditional Day of the Dead decorations.",
      de: "Eine Route durch die Straße, wo Sie beeindruckende künstliche Gräber und traditionelle Tag-der-Toten-Dekorationen finden.",
      fr: "Un parcours dans la rue où vous trouverez d'impressionnantes tombes artificielles et des décorations traditionnelles du Jour des Morts.",
      it: "Un percorso attraverso la strada dove troverai impressionanti tombe artificiali e decorazioni tradizionali del Giorno dei Morti.",
      zh: "穿过街道的路线，在那里您会发现令人印象深刻的人造墓穴和传统的亡灵节装饰。",
      ja: "印象的な人工墓と伝統的な死者の日の装飾が見られる通りのルート。",
      ru: "Маршрут по улице, где вы найдете впечатляющие искусственные гробницы и традиционные украшения Дня мертвых.",
    },
    routePoints: [
      [18.770577, -98.541242],
      [18.770329, -98.539604],
    ],
    routeColor: "#7FDBFF",
    image: "/arcos.png",
  },
  {
    id: 39,
    name: {
      es: "Zona de Eventos",
      en: "Event Zone",
      de: "Veranstaltungszone",
      fr: "Zone d'Événements",
      it: "Zona Eventi",
      zh: "活动区",
      ja: "イベントゾーン",
      ru: "Зона мероприятий",
    },
    type: "information",
    lat: 18.770205,
    lng: -98.541567,
    description: {
      es: "Área principal para eventos y presentaciones culturales durante la celebración del Día de Muertos.",
      en: "Main area for events and cultural presentations during the Day of the Dead celebration.",
      de: "Hauptbereich für Veranstaltungen und kulturelle Präsentationen während der Tag-der-Toten-Feier.",
      fr: "Zone principale pour les événements et les présentations culturelles pendant la célébration du Jour des Morts.",
      it: "Area principale per eventi e presentazioni culturali durante la celebrazione del Giorno dei Morti.",
      zh: "亡灵节庆祝活动期间的主要活动和文化展示区域。",
      ja: "死者の日の祝祭中のイベントや文化プレゼンテーションのメインエリア。",
      ru: "Основная зона для мероприятий и культурных презентаций во время празднования Дня мертвых.",
    },
  },
]);

export const info = writable<any>([]);
